### ISSUE TITLE
Systeminfo Memory faulty

### ISSUE THREAD

**Issue by eliteSchwein** [eliteSchwein/mooncord#200]
on not raspberry pi systems (or maybe raspberry pi systems aswell?)

Systeminfo Memory throws errors:

example:

```[error] [2022-01-10T08:06:57.855Z] DiscordAPIError: Invalid Form Body
embeds[0].fields[5].value: This field is required
            DiscordAPIError: Invalid Form Body
embeds[0].fields[5].value: This field is required
    at RequestHandler.execute (/home/odroid/mooncord/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/odroid/mooncord/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async MessageManager.edit (/home/odroid/mooncord/node_modules/discord.js/src/managers/MessageManager.js:132:15)
    at async ViewSystemInfo.execute (/home/odroid/mooncord/dist/index.js:49228:9)```

**Comment by eliteSchwein** [comment]
fixed with 29f346623026b06874941b1160bde166d17849bd
